project_id = "qbbubmlpjoghsbnjztyc"

[functions.ai-transcribe]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.generate-proposal]
verify_jwt = false

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.polish-text]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false
